--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ-Plugins/SimpleEconomy
build-by-default: true
branches:
- main
projects:
  SimpleEconomy:
    path: ""
    libs:
      - src: NhanAZ-Libraries/SimpleSQL/SimpleSQL
        version: ^1.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
...
